language: node_js
node_js:
  - "6"
  - "5"
before_script:
  - npm install -g karma
  - npm install -g karma-cli
script:
  - sudo ./node_modules/.bin/karma start karma.conf.babel.js --browsers PhantomJS --single-run
